name: intro_example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.3
  image_picker: ^0.8.4+11
  provider: ^6.0.2
  firebase_auth: ^4.2.2
  firebase_core: ^2.8.0
  firebase_ml_model_downloader: ^0.2.0+13
  cloud_firestore: ^4.4.5
  google_sign_in: ^6.0.2
  flutter_tflite: ^1.0.1
  intl: ^0.18.1
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  dio: ^5.4.3+1
  hexcolor: ^2.0.6
  shared_preferences: ^2.0.13
  lottie: ^1.3.0
  animated_splash_screen: ^1.2.0
  screenshot: ^1.2.3
  permission_handler: ^11.0.1
  image_gallery_saver: ^1.7.1
  flutter_launcher_icons: ^0.11.0
  firebase_storage: ^11.0.16
  adaptive_dialog: ^1.6.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_native_splash: any
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/icon.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ic_launcher.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/lottie_animations/
    - assets/tflite_models/
  fonts:
    - family: seguisb
      fonts:
        - asset: assets/seguisb.ttf
